### ISSUE TITLE
Is it possible to run cfbot with api access token

### ISSUE THREAD

**Issue by meantest** [jthomas/cfbot#5]
Hello
This is not really an issue but just want to know if it's possible to do. I am already having the oauth token from bluemix so it is possible to avoid getting cf_username and cf_password in cups.

**Comment by jthomas** [comment]
The application doesn't support this authentication scheme at the moment I'm afraid. We use the [https://www.npmjs.com/package/cf-nodejs-client](https://www.npmjs.com/package/cf-nodejs-client) client library for Cloud Foundry and it doesn't seem to support this either. 

If you want to attempt to get this working, please send a pull request 😀
