### ISSUE TITLE
bot user's goes to away state

### ISSUE THREAD

**Issue by suren04** [jthomas/cfbot#8]
Hi, 

I am seeing my bot user in slack going to away state after sometime..

Soon I restart the cfbot application in CF it becomes active again.

Is there any settings to tune this?

**Comment by jthomas** [comment]
I'm not actively using or maintaining this project anymore. If you are able to resolve this issue, feel free to send a PR?

What do the application logs show when this error occurs?

**Comment by jthomas** [comment]
I'm closing this issue due to the lack of activity.
