### ISSUE TITLE
Cfbot not working after pushing the application into space

### ISSUE THREAD

**Issue by Akhilesh-Anb** [jthomas/cfbot#9]
I pushed the application into cloud foundry and while starting the application, i'm getting the following error,

> 2017-06-03T18:05:17.630+05:30 [APP/PROC/WEB/0] [OUT] info: Ahoy! Attempting to start CF Bot...
> 2017-06-03T18:05:17.631+05:30 [APP/PROC/WEB/0] [OUT] info: Connecting to Slack using the following token: xoxb-xxxxxxxxxxxxxxxx
> 2017-06-03T18:05:17.632+05:30 [APP/PROC/WEB/0] [OUT] [Sat Jun 03 2017 12:35:17 GMT+0000 (UTC)] INFO Connecting...
> 2017-06-03T18:05:17.661+05:30 [APP/PROC/WEB/0] [ERR] error: Connection Error From Slack Websocket
> 2017-06-03T18:05:17.661+05:30 [APP/PROC/WEB/0] [OUT] [Sat Jun 03 2017 12:35:17 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
> 2017-06-03T18:05:17.661+05:30 [APP/PROC/WEB/0] [ERR] error: ENOTFOUND

**Comment by Akhilesh-Anb** [comment]
App is getting crashed continuously.

**Comment by jthomas** [comment]
I'm not actively using or maintaining this project anymore. If you are able to resolve this issue, feel free to send a PR?

If you run the application locally, do you get the same issue?
